### ISSUE TITLE
sandbox Invalid request ip

### ISSUE THREAD

**Issue by mymtw** [Kucoin/kucoin-python-sdk#27]
same as in title,
added withdrawal permission in sandbox,
my ip address did not change

my request:
```
user_client = User(key=api_key, secret=api_secret, passphrase=api_passphrase, is_sandbox=True)
user_client.get_withdrawal_quota('BTC')
```
Exception: 403-{"code":"400006","msg":"Invalid request ip"}

**Comment by codewc** [comment]
> code

The API for deposit and withdrawal in the sandbox environment is not supported. Because it's just a test environment
In addition, On the dashboard enabling “Transfer” permission requires whitelisting api addresses
Although you have configured the correct ip whitelist, in fact the whitelist of the sandbox environment is not effective.
In summary:
1. the "Transfer" permission is disabled
2. `IP Restriction`, Check the `No` option
