### ISSUE TITLE
How to add balance to sandbox account

### ISSUE THREAD

**Issue by acairon** [Kucoin/kucoin-python-sdk#31]
hello is there anyway to add balance to a sandbox account? thanks

**Comment by codewc** [comment]
> hello is there anyway to add balance to a sandbox account? thanks

The sandbox environment will give the account a certain amount of USDT by default, and because it is a test environment, it is not possible to deposit and withdraw
If you really need to deposit other currencies, please tell me the currency and quantity you need to deposit, and also tell me the email address registered in the sandbox environment
