### ISSUE TITLE
client.create_market_order do nothin  on sandbox

### ISSUE THREAD

**Issue by acairon** [Kucoin/kucoin-python-sdk#33]
im trying to 

client = Trade(key=api_key, secret=api_secret, passphrase=api_passphrase, is_sandbox=True)

print(client.create_market_order('BTC-USDT', 'buy', funds='100'))

and creates an order id , but then in the control panel of kucoin sandbox it dident buy btc

**Comment by Alan-Edmonds** [comment]
Thanks. I had the same issue and this fixed it. But why is this, why can I only trade kcs-usdt?

**Comment by codewc** [comment]
> Thanks. I had the same issue and this fixed it. But why is this, why can I only trade kcs-usdt?

Because the sandbox environment is simulated, only the `KCS-USDT` trading pair is currently simulated

**Comment by ISAAC-XXYYZZ** [comment]
Due to many changes in the SDK, please refer to our latest documentation.
 https://www.kucoin.com/docs/beginners/introduction
Since this issue has had no updates for a long time, we will now close it. Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
