### ISSUE TITLE
ORDER_MARKET_STOP in create_limit_order or create_market_order? And how to use?

### ISSUE THREAD

**Issue by SyntaxJO** [Kucoin/kucoin-python-sdk#44]
I am trying to figure out ORDER_MARKET_STOP (or ORDER_LIMIT_STOP), but I'm not sure if I'm supposed to use in the the create_market_order or in the create_limit_order with a stop option.

I have vigorously tried with both to no success. I figure it would work in create_limit_order, I add STOP_LOSS, it asks for stop_price

I am stuck with limit orders which earmark my funds for each order and make it impossible to place multiple "stops." So I am still placing stops manually.

Thank you for your great work on this! It's a life saver.

**Comment by ISAAC-XXYYZZ** [comment]
Due to many changes in the SDK, please refer to our latest documentation.
 https://www.kucoin.com/docs/beginners/introduction

Since this issue has had no updates for a long time, we will now close it. Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
