### ISSUE TITLE
Trade Market order fails with requests.exceptions.ReadTimeout

### ISSUE THREAD

**Issue by arqn** [Kucoin/kucoin-python-sdk#56]
Trying to make an spot order in Sandbox gets mi the next error: ' requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='openapi-sandbox.kucoin.com', port=443): Read timed out'

I'm runing the script from a local env with pycharm  and making a basic API request, not using websocket
i tried it with python 3.8, 3.9 and 3.10

any suggestion?

this is my basic code: 

from kucoin.client import Market
from kucoin.client import Trade

client = Market(url='https://openapi-sandbox.kucoin.com')
client = Market(is_sandbox=True)

client = Trade(api_key, api_secret, api_passphrase, is_sandbox=True)
order_id = client.create_market_order('BTC-USDT', 'buy', size='1')

**Comment by pavitrakumar78** [comment]
Hi,

I have the same issue with even the account orders history endpoint. Did you find any solution for this?

**Comment by ehgp** [comment]
I think this is because sandbox is not well maintained by Kucoin. For the websocket component of the account balance and trade orders I get a 500 server error. For the trade API I get a server timeout. They are not even keeping up the servers. That is too bad considering my master's project deals with using a sandbox trading environment. Anyone know of a reputable one?

**Comment by ISAAC-XXYYZZ** [comment]
Sorry for the late reply. Our sandbox environment has been decommissioned for now.
Due to many changes in the SDK, please refer to our latest documentation: https://www.kucoin.com/docs/beginners/introduction
Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
