### ISSUE TITLE
market api get_aggregated_orderv3 error

### ISSUE THREAD

**Issue by Conteduca** [Kucoin/kucoin-python-sdk#60]
When I try executing the function get_aggregated_orderv3 I receive the following error
Exception: 400-{"code":"400001","msg":"Please check the header of your request for KC-API-KEY, KC-API-SIGN, KC-API-TIMESTAMP, KC-API-PASSPHRASE"}

Take into account that I am using the library and all other functions seem to work.

**Comment by banegil** [comment]
same error, in theory is a public method, you can solve it just sign in like a private method, but it is really uncomfortable

**Comment by ISAAC-XXYYZZ** [comment]
Due to many changes in the SDK, please refer to our latest documentation.
 https://www.kucoin.com/docs/beginners/introduction

Since this issue has had no updates for a long time, we will now close it. Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
